use main_project;

drop table if exists `announcement`;

CREATE TABLE announcement (
    announcement_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title TEXT,
    content TEXT,
    announcement_date date,
    announcement_day varchar(20),
    passed_by_emp_id BIGINT,
    approved_by_emp_id BIGINT,
    FOREIGN KEY (passed_by_emp_id) REFERENCES employee(emp_id),
    FOREIGN KEY (approved_by_emp_id) REFERENCES employee(emp_id)
);

select * from `announcement`;


INSERT INTO `main_project`.`announcement` (`title`, `content`, `announcement_date`, `passed_by_emp_id`, `approved_by_emp_id`) VALUES ('Investment Declaration - FY 2023-24 - Income Tax', 'Dear All,\\n As per the recent Budget for FY 2023-24, Default Tax computation in Keka will be under \"New Tax Regime\". If you have Investment & tax savings that makes Old tax regime as beneficial, you have the option in Keka to switch to Old Tax Regime. [You can either choose the option via the Pop-up generated by Keka while login or you can navigate to \"My Finances => My Pay => Above your current compensation there will be a link to opt for Old tax Regime\".', '2023-01-10', '2', '1');



select * from `announcement`;
